version: '3.8'
services:
  app:
    build: ./
    container_name: app
    restart: ${RESTART_POLICY}
    networks:
      - backend
    environment:
      - TZ
      - SERVER_PORT
      - REDIS_URL
      - REDIS_PASSWORD
      - USER_CACHE_EXPIRATION_MS
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

  redis:
    image: bitnami/redis:${REDIS_IMAGE_TAG}
    container_name: redis
    restart: ${RESTART_POLICY}
    networks:
      - backend
    environment:
      - TZ
      - REDIS_PASSWORD
    volumes:
      - redis_data:/bitnami/redis/data
    ports:
      - 6379:6379

networks:
  backend:
    driver: bridge
    name: backend

volumes:
  redis_data:
    driver: local
    name: redis_data